services:
  selenoid:
    image: aerokube/selenoid:latest-release
    container_name: selenoid
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/Documents/Docker/Selenoid/config/:/etc/selenoid/:ro

  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    container_name: selenoid-ui
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "80:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
