name: Deploy to production

on: workflow_call

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy backend to production
        run: echo "Deploying backend"

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy frontend to production
        run: echo "Deploying frontend"
