name: Frontend deployment

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build frontend
        run: echo "Building frontend, running tests and publishing a new Docker image"

  deploy-stage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy frontend to stage / review app
        run: echo "Deploying frontend"
